modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="time_engine"
version="${version}"
displayName="Time Engine"
authors="kaila"
description='''
An experimental time and speed mechanics mod.
'''

[[dependencies.time_engine]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.time_engine]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
